[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sponsor"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/sponsors"
  to = "/"
  status = 301
  force = true
