[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sponsor"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/sponsors"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/route"
  to = "/route.html"
  status = 200
  force = false

[[headers]]
  for = "/route.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
